# Generated by Django 4.0 on 2022-01-18 02:29

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Enter task title', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Enter task description', max_length=1000, null=True)),
                ('start', models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 7, 0, 0), help_text='Enter the date to start working on the task', null=True)),
                ('due', models.DateTimeField(default=datetime.datetime(2024, 6, 7, 23, 59, 59, 999999), help_text='Enter the date the task is due')),
                ('complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['due', 'complete'],
            },
        ),
    ]
