# Generated by Django 4.0 on 2022-01-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Enter task title', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Enter task description', max_length=1000, null=True)),
                ('start', models.DateTimeField(blank=True, help_text='Enter the date to start working on the task', null=True)),
                ('due', models.DateTimeField(help_text='Enter the date the task is due')),
                ('complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['due', 'complete'],
            },
        ),
    ]
