# Generated by Django 4.0 on 2021-12-19 23:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 19, 23, 59, 18, 371021, tzinfo=utc), help_text='Enter the date the task is due'),
        ),
    ]
