# Generated by Django 4.0 on 2022-04-22 17:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 0, 0, tzinfo=utc), help_text='Enter the date to start working on the task'),
        ),
    ]
