# Generated by Django 5.0.3 on 2024-08-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='show_due_time',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='show_start_time',
            field=models.BooleanField(default=True),
        ),
    ]
