# Generated by Django 4.0 on 2022-07-11 23:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_due_alter_task_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 11, 23, 59, 59, 999999, tzinfo=utc), help_text='Enter the date the task is due'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 11, 0, 0, tzinfo=utc), help_text='Enter the date to start working on the task'),
        ),
    ]
