# Generated by Django 4.0 on 2021-12-29 22:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_task_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 29, 23, 59, 40, 419331, tzinfo=utc), help_text='Enter the date the task is due'),
        ),
    ]
