# Generated by Django 4.0 on 2022-01-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_task_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due',
            field=models.DateTimeField(help_text='Enter the date the task is due'),
        ),
    ]
