# Generated by Django 4.0 on 2022-01-05 06:09

from django.db import migrations


def create_data(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    Task(title="Buy flight", 
        complete=False,
        completed_at=None,
        start="2021-12-21T06:13:45Z",
        due="2021-12-24T06:13:52Z",
        description="Delta is cheaper. I have a card with them too").save()

    Task(title='Fill out TA application',
        complete=False,
        completed_at=None,
        start='2021-12-01T06:14:42Z',
        due='2022-01-03T06:14:34Z',
        description='').save()

    Task(title='Buy Zuzu a cat carrier',
        complete=False,
        completed_at=None,
        start=None,
        due='2022-01-05T06:14:17Z',
        description='').save()

    Task(title='Work on Quill!!!',
        complete=False,
        completed_at=None,
        start='2021-12-22T06:15:05Z',
        due='2022-01-22T06:15:12Z',
        description='Lots to do, lots to do....').save()
    
    Task(title='Important: Party at home alone in my room',
        complete=False,
        completed_at=None,
        start='2022-01-02T06:15:42Z',
        due='2022-01-22T06:15:47Z',
        description='').save()
    
    Task(title='Be awesome 😎',
        complete=True,
        completed_at='1999-11-28T06:16:05Z',
        start='1999-11-28T06:16:05Z',
        due='2100-11-28T06:16:49Z',
        description='').save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_task_due'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
