# Generated by Django 4.0 on 2021-12-15 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_task_start_alter_task_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 14, 23, 59, 12, 352191), help_text='Enter the date the task is due'),
        ),
    ]
